### ISSUE TITLE
[Bug] RSS: Affected feeds sometimes missing

### ISSUE THREAD

**Issue by merv1n** [VueTorrent/VueTorrent#1426]
Affected feeds in RSS rules sometimes do not display. Sometimes the heading “Affected feeds” and buttons “Select all”, “Select none” are also missing. I’m using Chrome on my iPad and VueTorrent 2.4.0.

![IMG_0379](https://github.com/WDaan/VueTorrent/assets/34961694/bed371f6-d49d-43d2-b665-db80376b9685)

**Comment by CharlesLTH** [comment]
I am encountering a similar issue.
When I try to add RSS rules, the entries in the ‘Affected feeds’ section do not display. 
I need to first visit the Feeds page and then return to the Rules page. After doing this, the entries in the ‘Affected feeds’ section display correctly.
I am unsure whether this issue is related to qBittorrent or Vue.

I’ve tested this on both PC Chrome and iPhone Safari, using qBittorrent version 4.6.2.10 and Vue version 2.4.0.

![图像](https://github.com/WDaan/VueTorrent/assets/33312999/43fb7c64-3635-4517-9c09-31cf6987d0d4)
