### ISSUE TITLE
[Feature Request]: Sidebar should not be open on launch

### ISSUE THREAD

**Issue by romartobashey** [VueTorrent/VueTorrent#1804]
### Description

The setting is gone for whatever reason, messes up the table view on the iPad. 

### Describe the solution you'd like

Restore the setting

### Describe alternatives you've considered

Change the default behavior

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by WDaan** [comment]
Solved in 2.11.0?

**Comment by Larsluph** [comment]
> Solved in 2.11.0?

iPads may be recognized as desktop so the navbar opens by default. We can increase the threshold to prevent from opening on medium screen sizes.

**Comment by Larsluph** [comment]
And just as a side note, you can hide the navbar by clicking on the top burger icon next to the app title

![image](https://github.com/user-attachments/assets/236b6b78-3c8a-428c-80b4-6da48a9b280c)

**Comment by romartobashey** [comment]
Sorry, I just saw the responses.

> And just as a side note, you can hide the navbar by clicking on the top burger icon next to the app title
> 
> ![image](https://private-user-images.githubusercontent.com/22910497/351407541-236b6b78-3c8a-428c-80b4-6da48a9b280c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzc2MDcsIm5iZiI6MTcyMjI3NzMwNywicGF0aCI6Ii8yMjkxMDQ5Ny8zNTE0MDc1NDEtMjM2YjZiNzgtM2M4YS00MjhjLTgwYjQtNmRhNDhhOWIyODBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE4MjE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NDQ3ZGI3ZGMzYWM2YTlmMDdiODRkNmU4YmFiZjQ1NjQwZWIwNTc2ODUzZWVkZDA2ODAxZmNiNGU5ZDQxNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wbIsOuOP2mGT3Z4rkkJ9IrQSIxwye7oRMc4vJT3t98w)

Oh, come on, you’ve got to give me a little more credit than that😀.


> Solved in 2.11.0?

The option to hide the sidebar was only removed in 2.11. I think that even if the setting was deemed redundant, it makes more sense to have the sidebar hidden on launch by default. I shouldn’t even have mentioned the iPad, my criticism applies to the desktop version as well: it changes the table view layout by hiding the rightmost column(s), and kind of visually clashes with the torrent table (especially when using the light theme). In other words, I always assumed the sidebar’s functionality and appearance suggested it should be looked at as something to be invoked occasionally, to look at stats or add a tracker filter, not to have it always visible. It’s obviously a personal preference, and I may be wrong to assume most people use torrent clients the same way I do, so it still makes most sense to me to leave that as an option.

I think there was a pagination indicator setting that was also removed in this version, similarly making the UI a little messier. I always appreciated these granular, nit-picky settings, they were thoughtful and made the client better for everyday use. I’d like more of them, not fewer! Anyway, I love VueTorrent, it’s so much better to look at and, in many ways, to use than the native web UI (and even the client itself), but these changes just don’t make sense to me.

**Comment by Larsluph** [comment]
> Oh, come on, you’ve got to give me a little more credit than that😀.

I just prefer to make sure 😄 

> I think that even if the setting was deemed redundant, it makes more sense to have the sidebar hidden on launch by default. I shouldn’t even have mentioned the iPad, my criticism applies to the desktop version as well: it changes the table view layout by hiding the rightmost column(s), and kind of visually clashes with the torrent table (especially when using the light theme).

Navbar has been designed to hold information that may be useful throughout the entire app. Also a quick history note, only the list layout existed at first. Grid and table layouts has been added after that so the navbar may need adjustments before fitting everyone's needs.
Unfortunately, the table view is the only one that doesn't wrap when overflowing. Because the width depends on the properties you display but also the size of columns' content, we can't really "hard-code" some rules to display it or not, even using the layout used as a base.

> In other words, I always assumed the sidebar’s functionality and appearance suggested it should be looked at as something to be invoked occasionally, to look at stats or add a tracker filter, not to have it always visible. It’s obviously a personal preference, and I may be wrong to assume most people use torrent clients the same way I do

You're exactly right and because we have a lot of different users, there will be deceptions for some people.

> so it still makes most sense to me to leave that as an option

Just to justify why I decided to remove it, if you use the backend (which I do), settings are synchronized between clients regardless of the screen size.
That means that before the update, if I wanted to open the navbar by default on desktop, it would automatically open on mobile which I don't want. But the other way was still problematic as it would be closed on mobile but also on desktop.

I thought about bypassing that settings on mobile but then there would be a "useless" option for mobile users which is not great.

> I think there was a pagination indicator setting that was also removed in this version, similarly making the UI a little busier.

> This was something I always wanted because when using long page sizes, having the pagination only at the top or at the bottom would be really frustrating because it depends on the moment. I removed that option and displayed them both to prevent that.

You mentioned that it takes a lot of space, a quick fix has been pushed to merge it into the empty space on desktop. It's always complicated to make everything fit on mobile so we can't do anything about it.

> I always appreciated these granular, nit-picky settings, they were thoughtful and made the client better for everyday use. I’d like more of them, not fewer! Anyway, I love VueTorrent, it’s so much better to look at and, in many ways, to use than the native web UI (and even the client itself), but these changes just don’t make sense to me.

I totally agree and personally love when you can configure your tools to fit your needs perfectly. But this kind of fully configurable interface is something a lot of people find very confusing and get lost in the variety of settings. We try to fit as much users as we can but again it may need some adjustments that needs time to find the perfect mix between all profiles.

**Comment by romartobashey** [comment]
Thank you for the thorough and thoughtful reply.

> Also a quick history note, only the list layout existed at first. Grid and table layouts has been added after that so the navbar may need adjustments before fitting everyone's needs.

I actually knew that. I first tried using VueTorrent quite a long time ago (around 2 years maybe?) and liked it on mobile but had to abandon it after realizing it wasn't optimized for the desktop yet. I tried it again ~6 months ago after seeing how much development there had been in the meantime, and I never even considered switching back after realizing how much faster it'd become and how good the table layout was on the desktop and the iPad (I even use it on my phone now). 

> Navbar has been designed to hold information that may be useful throughout the entire app.

There's a lot of very useful stuff there, but I find that, save for an occasional tracker filter, I rarely have to open the navbar because I almost always use the very handy state, tag and category filter shortcuts on the top bar. Also, considering the much lower density of the UI in VueTorrent compared to desktop clients, it's not just a preference but rather a necessity for my lower-res screens to have the navbar hidden to comfortably use it.

> This was something I always wanted because when using long page sizes, having the pagination only at the top or at the bottom would be really frustrating because it depends on the moment. I removed that option and displayed them both to prevent that.
> 
> You mentioned that it takes a lot of space, a quick fix has been pushed to merge it into the empty space on desktop. It's always complicated to make everything fit on mobile so we can't do anything about it.

That's great! That one, unlike the navbar thing, didn't really bother me much. I also agree that having the pagination both at the top and at the bottom feels right. 

> Just to justify why I decided to remove it, if you use the backend (which I do), settings are synchronized between clients regardless of the screen size.
> That means that before the update, if I wanted to open the navbar by default on desktop, it would automatically open on mobile which I don't want. But the other way was still problematic as it would be closed on mobile but also on desktop.

I see. I didn't know that, now it makes sense. It would be pretty annoying to have it automatically open on mobile.

I have to say, I tried using the updated version again after rolling back the update last week, and I still can't get used to it being open even on the desktop, and it's not just an aesthetic preference: I'm sure it works fine on a 4K+ display, but the navbar takes way too much space on my lower resolution screen: I either have to remove 2 columns to see the full layout with the navbar open, or I have to hide the navbar each time I open VueTorrent. 

I took a look at the code and wondered if maybe you could consider having the breakpoint set to 'xl' instead of 'md' as a middle ground? Or even better:

> I thought about bypassing that settings on mobile but then there would be a "useless" option for mobile users which is not great.

Wouldn't just changing the name of the setting to "Open sidebar on launch on the desktop" solve it? A little wordy, but still better than removing the option altogether IMO. 

Preserving the open/closed state across launches would, of course, be ideal, but probably too complicated?

In any case, thanks again for taking the time to explain the nuances and difficulties of making VueTorrent work well on multiple platforms while managing the needs and expectations of very different types of users, I appreciate it.

**Comment by Larsluph** [comment]
> I took a look at the code and wondered if maybe you could consider having the breakpoint set to 'xl' instead of 'md' as a middle ground?

Not a big fan of the idea of removing it by default for a lot of users (including me 👀), from [Vuetify docs](https://vuetifyjs.com/en/features/display-and-platform/#breakpoints-and-thresholds) `xl` breakpoint is for displays larger than (excluding) 1920 pixels wide.

> Wouldn't just changing the name of the setting to "Open sidebar on launch on the desktop" solve it? A little wordy, but still better than removing the option altogether IMO.

This could be done but there would still be a useless option for mobile, even if it's explicitly said.

> Preserving the open/closed state across launches would, of course, be ideal, but probably too complicated?

This could be done really easily and could be a great replacement for the original option.

We may still have users that will complain because they use privacy-focused browsers that cleans their local storage after each session, in that case we can't do much about it so I wouldn't take it into considerations...

> In any case, thanks again for taking the time to explain the nuances and difficulties of making VueTorrent work well on multiple platforms while managing the needs and expectations of very different types of users, I appreciate it.

This means a lot! 🙌🙏
