### ISSUE TITLE
[Bug]: Exporting multiple torrents fails when including cross-seeds

### ISSUE THREAD

**Issue by SawkeeReemo** [VueTorrent/VueTorrent#1893]
### Bug description

When I select multiple torrents to export, if one of them includes a cross-seeded torrent, the export just doesn't happen, and there is no dialog as to why.

I wanted to check to see how exporting multiple torrents now worked when dealing with cross-seeds, which was [another issue posted here](https://github.com/VueTorrent/VueTorrent/issues/1741). But when I tried to do this, selecting multiple torrent, then right-click > export... nothing happens. If I deselect any cross-seeds, then it will export to a .zip file as expected.

### Expectations

To be able to export multiple torrents, including any cross-seeds.

### Relevant debug informations

Can only refer back to my original request:
https://github.com/VueTorrent/VueTorrent/issues/1741

### Steps to reproduce

1. Select multiple torrents, including some cross-seeds
2. right-click
3. choose Export torrents

### How did you install VueTorrent?

Using a third-party docker image (hotio or others)

### Environment description

```plain text
Host device:
Device type: Synology NAS [DS1019+]
OS: DSM 7.2.1 & Docker v20.10.23

Client device:
Device type: Mac Pro [trash can]
OS: macOS 12.7.6 Monterey
Browser (name and version): Chrome 128.0.6613.115


PWA: Yes / No (not sure what this is? ... Piglets With Attitudes? then....yes....)
Running inside a container: Yes
```

### qBittorrent version

4.6.5

### VueTorrent version

2.12.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
When you say cross-seed, do you mean duplicate torrents with a different hash?

By duplicate I mean the same name and content.

**Comment by SawkeeReemo** [comment]
Right. The same torrent uploaded to two different sites. So you’ve downloaded it once, but are seeding it two two or more trackers at the same time.

So the filename would be the same, but the hash is different. I think we talked about a solution being to use the torrent name, then a truncated hash at the end of the file name to help keep them unique upon export.

**Comment by Larsluph** [comment]
Can you check errors in the DevTools?
Just to be sure about the exact reason why the zip file isn't generated.

**Comment by SawkeeReemo** [comment]
> Can you check errors in the DevTools? Just to be sure about the exact reason why the zip file isn't generated.

Happy to do so, but I'm going to need a little guidance there. I'm not a developer myself, so I'm largely unfamiliar with how to  effectively interact with DevTools in a browser. Where/what specifically should I be looking at?

**Comment by Larsluph** [comment]
You can look at the [support page of the wiki](https://github.com/VueTorrent/VueTorrent/wiki/Support), everything's explained there!

**Comment by Larsluph** [comment]
@SawkeeReemo Any news on that?

**Comment by maksii** [comment]
![image](https://github.com/user-attachments/assets/ea715b47-1117-4fb9-ac3f-1ed2b0e7a33e)
the problem is not cross-seeds, but the same name of torrents when exporting.
The api request for export is successful, but in the logic of the zip archive compilation we get a problem, since the files will have the same name.
To solve this problem, I would suggest including an item in the settings where you could optionally add a category and a tag to the file name in the format like this(If we do have a duplicate even under these conditions, then add a digit to the end)

`{torrent_name}_{category_name}_{tags}`

Steps to Reproduce bug:
Rename two torrents to have the same name.
Select two torrents
Click Exports torrents

Expected result: torrents.zip generated and downloaded by browser
Actual result: nothing happens

as a minimally logical solution to this problem it is necessary to at least show the error that the request was unsuccessful with its cause.

affected line
`await Promise.all(u.value.map(ie => d.exportTorrent(ie).then(ae => Y.add(`${d.getTorrentByHash(ie).name}.torrent`, new fl(ae)))))`
