### ISSUE TITLE
[Feature Request]: Make setting persistent

### ISSUE THREAD

**Issue by terrytw** [VueTorrent/VueTorrent#1918]
### Description

It seems that the setting of vuetorrent is stored in the browser session, so if I use incognito mode, the settings are not persistent.

There is the option to export and import setting, however it is still cumbersome if I have to do it every time.

Also, there is not setting related to default view (list, table, grid) and sort order, so even if I export and import settings, that is not restored. 

### Describe the solution you'd like

Maybe an option to save settings (including default view and sort order) to disk is possible?

### Describe alternatives you've considered

I can hack `vuetorrent.ts` and `DashboardDefaults.ts`, but it's obviously not a great idea...

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
File System API is another permission that requires a secure context (HTTPS or localhost).
We could use that but it would need some configuration anyway to make it work.

Incognito mode is not just a special mode but instead creates a temporary user that stores all its data into memory instead of your disk.

I would recommend using [the backend](https://github.com/VueTorrent/vuetorrent-backend) instead, now that it is able to auto-configure itself.
You need to run it alongside qBittorrent to make it work.

**Comment by terrytw** [comment]
Thanks for the suggestions, I looked into the backend, it looks promising for my use case, however one thing is weird: after logging in, I have to refresh the page before my settings kick in, before refresh, the page is displaying the default configs.

**Comment by Larsluph** [comment]
Could you send the requests' list so that I can investigate? (you can filter `/backend`) A screenshot is enough, I just need to see the timeline of requests to the backend.

Check out the [Support page](https://github.com/VueTorrent/VueTorrent/wiki/Support) for instructions

**Comment by terrytw** [comment]
![1](https://github.com/user-attachments/assets/3f2435e4-6545-4c9f-aaad-0a07c322c36c)

I don't know whether it is related, I host the backend under a subpath suing caddy:

```
	redir /vue /vue/
	handle_path /vue* {
		reverse_proxy IP:PORT {
			header_up Host IP:PORT
			header_up -Origin
			header_up -Referer
		}
	}
```

**Comment by Larsluph** [comment]
Yeah, that's also what I think seeing these.

I'll take a look when I have time.
