### ISSUE TITLE
latest-release branch is behind actual latest release

### ISSUE THREAD

**Issue by fexofenadine** [VueTorrent/VueTorrent#1926]
latest-release branch is showing version 2.13.0-9-gc5de1d31, but releases page is at v2.13.1, so doing a git pull on the latest-release branch is a bit behind ATM

not a big issue by any means!

**Comment by Larsluph** [comment]
If you look closely, both are refering to the same commit, one's before tagging and the other is after tagging. I updated the release assets manually afterwards, that's why the correct version's there.

I already tried some fixes (cf #1909 and #1923) but because it's a CI, we can only test at release time. Next release should be back to normal but we never know.

**Comment by fexofenadine** [comment]
aha, thank you for looking into it
