### ISSUE TITLE
[Bug]: Error "Incorrect HTTP request method will close the socket" appeared

### ISSUE THREAD

**Issue by 1298345095** [VueTorrent/VueTorrent#1942]
### Bug description

Error: Incorrect HTTP request method will close the socket. IP：::ffff:192.168.1.xx。 Method: "PUT"
appeared in qb's log when I open vuetorrent webui.

### Expectations

The error shouldn't appeared.

### Relevant debug informations

Whether I use qb or qbee, error occurs.

### Steps to reproduce

Just need to open the webui.

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
OS: Linux (Unraid)
Running inside a container: Yes (johngong/qbittorrent)
```

### qBittorrent version

4.6.7

### VueTorrent version

2.13.0-9-gc5de1d31

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
Linked to #1919, this is caused by the settings sync to the backend. qBittorrent disallows POST requests on unknown routes.

Tried it on my instance and no logs showed up though...

**Comment by 1298345095** [comment]
> Linked to #1919, updated description to include this use case.链接到 #1919 ，更新了描述以包含此用例。
> 
> This is caused by the settings sync to the backend. qBittorrent disallows POST requests on unknown routes.这是由于设置同步到后端造成的。 qBittorrent 不允许未知路由上的 POST 请求。
> 
> Tried it on my instance and no logs showed up though...在我的实例上尝试过，但没有显示日志......

Sorry, I don't know what you mean. Did you mean it should be solved by install vuetorrent-backend?

**Comment by Larsluph** [comment]
Because of the way we currently handle backend, we have no way to tell if it is present or not.

The settings sync is made by a plugin and we don't have any control on it ATM. The linked issue is the one that will rewrite all the sync system to prevent sync calls when the backend is not in use.

The POST request that logs a warning is a settings sync one, targeted at the backend. Because you don't have the backend, qBittorrent receives it but don't understand it (which is normal), thus logging a warning.

Sorry for not being clear enough.
