### ISSUE TITLE
No status bar background on iOS PWA

### ISSUE THREAD

**Issue by VEWION** [VueTorrent/VueTorrent#545]
Device: iPhone 11 on iOS16.1
VueTorrent installed as PWA and there is no background on the status bar so that the content will show up on the status bar while scrolling.
Also it makes the status bar icons hard to see when using light theme.
![F14B097D-89C6-4089-8CBF-172E703F6FB4](https://user-images.githubusercontent.com/56110451/202706829-84ae31a6-150f-48e8-adf5-9666656abddb.jpeg)

Another question: Is it possible to make VueTorrent follow system theme(Light/Dark mode)?

**Comment by WDaan** [comment]
Thanks for reporting! I've noticed as well. Haven't found a way to fix it yet though 🙁 I thought it was just setting [this](https://github.com/WDaan/VueTorrent/blob/master/index.html#L8) but apparently there's more too it.

> Another question: Is it possible to make VueTorrent follow system theme(Light/Dark mode)?

There's been an issue about this in the past, and the functionality was deemed to jittery. Because the darkTheme setting is stored and you only ever need to set it once, we thought it was not worth the effort.

**Comment by VEWION** [comment]
> Thanks for reporting! I've noticed as well. Haven't found a way to fix it yet though 🙁 I thought it was just setting [this](https://github.com/WDaan/VueTorrent/blob/master/index.html#L8) but apparently there's more too it.
> 
> > Another question: Is it possible to make VueTorrent follow system theme(Light/Dark mode)?
> 
> There's been an issue about this in the past, and the functionality was deemed to jittery. Because the darkTheme setting is stored and you only ever need to set it once, we thought it was not worth the effort.

Would it be good to use a solid black background with white letters as a temporary solution since there seems to be no easy solution at the moment?

**Comment by cybersholt** [comment]
Tested with iOS 16.5.1 with Apple iPad 9th Gen MK2K3LL/A with VT 2.6.0, looks great now!
